WITH RECURSIVE CTE AS (SELECT ID, PARENT_ID, 1 AS GENERATION 
                       FROM ECOLI_DATA 
                       WHERE PARENT_ID IS NULL
                      
                       UNION ALL
                       
                       SELECT ED.ID, ED.PARENT_ID, C.GENERATION+1
                       FROM CTE C INNER JOIN ECOLI_DATA ED ON C.ID = ED.PARENT_ID
                      )

SELECT COUNT(*) AS COUNT, GENERATION
FROM CTE 
WHERE ID NOT IN (SELECT DISTINCT PARENT_ID FROM CTE WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY 2
