WITH TBL AS(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (B.MAX_SIZE-E.SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA E INNER JOIN TBL B ON YEAR(E.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY 1,2