SELECT SUM(SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_DEPARTMENT D, HR_EMPLOYEES E, HR_GRADE G
WHERE D.DEPT_ID = E.DEPT_ID AND E.EMP_NO = G.EMP_NO
GROUP BY G.EMP_NO,G.YEAR
HAVING YEAR='2022'
ORDER BY 1 DESC
LIMIT 1